/*

 ENGINEDMGBAT4MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Engine\res\raw tiles\engineDMGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define engineDMGBat4MapWidth 1
#define engineDMGBat4MapHeight 5
#define engineDMGBat4MapBank 0

const unsigned char engineDMGBat4Map[] =
{
  0x31,0x32,0x35,0x34,0x33
};

/* End of ENGINEDMGBAT4MAP.C */
