/*

 ENGINEDMGBAT1MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Engine\res\raw tiles\engineDMGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define engineDMGBat1MapWidth 1
#define engineDMGBat1MapHeight 5
#define engineDMGBat1MapBank 0

const unsigned char engineDMGBat1Map[] =
{
  0x30,0x30,0x35,0x30,0x30
};

/* End of ENGINEDMGBAT1MAP.C */
