/*

 ENGINEDMGBAT3MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Engine\res\raw tiles\engineDMGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __engineDMGBat3Map_h_INCLUDE
#define __engineDMGBat3Map_h_INCLUDE

#define engineDMGBat3MapWidth 1
#define engineDMGBat3MapHeight 5
#define engineDMGBat3MapBank 0

extern const unsigned char engineDMGBat3Map[];

#endif

/* End of ENGINEDMGBAT3MAP.H */
