/*

 ENGINEDMGBAT0MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Engine\res\raw tiles\engineDMGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __engineDMGBat0Map_h_INCLUDE
#define __engineDMGBat0Map_h_INCLUDE

#define engineDMGBat0MapWidth 1
#define engineDMGBat0MapHeight 5
#define engineDMGBat0MapBank 0

extern const unsigned char engineDMGBat0Map[];

#endif

/* End of ENGINEDMGBAT0MAP.H */
