/*

 ENGINEDMGBAT3MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Engine\res\raw tiles\engineDMGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define engineDMGBat3MapWidth 1
#define engineDMGBat3MapHeight 5
#define engineDMGBat3MapBank 0

const unsigned char engineDMGBat3Map[] =
{
  0x30,0x32,0x35,0x34,0x30
};

/* End of ENGINEDMGBAT3MAP.C */
