/*

 ENGINEDMGBAT0MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Engine\res\raw tiles\engineDMGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define engineDMGBat0MapWidth 1
#define engineDMGBat0MapHeight 5
#define engineDMGBat0MapBank 0

const unsigned char engineDMGBat0Map[] =
{
  0x30,0x30,0x36,0x30,0x30
};

/* End of ENGINEDMGBAT0MAP.C */
