/*

 ENGINEDMGBAT1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Engine\res\raw tiles\engineDMGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __engineDMGBat1Map_h_INCLUDE
#define __engineDMGBat1Map_h_INCLUDE

#define engineDMGBat1MapWidth 1
#define engineDMGBat1MapHeight 5
#define engineDMGBat1MapBank 0

extern const unsigned char engineDMGBat1Map[];

#endif

/* End of ENGINEDMGBAT1MAP.H */
