/*

 TEMPLATEFACE1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 2 x 2
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Template\res\raw tiles\templateFaceTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 64
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __templateFace1Map_h_INCLUDE
#define __templateFace1Map_h_INCLUDE

#define templateFace1MapWidth 2
#define templateFace1MapHeight 2
#define templateFace1MapBank 1

extern const void __bank_templateFace1Map;
extern const unsigned char templateFace1Map[];

#endif

/* End of TEMPLATEFACE1MAP.H */
