#pragma bank 1

/*

 TEMPLATEFACE2MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 2 x 2
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Template\res\raw tiles\templateFaceTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 64
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define templateFace2MapWidth 2
#define templateFace2MapHeight 2
#define templateFace2MapBank 1

const void __at(1) __bank_templateFace2Map;
const unsigned char templateFace2Map[] =
{
  0x44,0x46,0x45,0x47
};

/* End of TEMPLATEFACE2MAP.C */
