#pragma bank 13

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(bbbbbr_stars)

const palette_color_t bbbbbr_stars_palettes[4] = {
	RGB8(0, 0, 0), RGB8(255, 255, 255), RGB8(160, 160, 160), RGB8(0, 0, 0)
};

const uint8_t bbbbbr_stars_tiles[128] = {
	0x00,0x00,0x00,0x00,0x00,0x01,0x01,0x02,0x01,0x02,0x03,0x04,0x03,0x7c,0x3f,0x40,
	0x00,0x00,0x00,0x00,0x00,0x80,0x00,0xc0,0x00,0xe0,0x80,0x60,0x80,0x7e,0xf8,0x06,
	0x1f,0x20,0x07,0x18,0x07,0x08,0x0f,0x10,0x0c,0x33,0x18,0x27,0x00,0x3e,0x00,0x1c,
	0xf0,0x0e,0xc0,0x3c,0xc0,0x38,0xe0,0x18,0x60,0x9c,0x30,0xcc,0x00,0x7c,0x00,0x3c,
	0x00,0x00,0x00,0x00,0x01,0x01,0x02,0x03,0x02,0x03,0x04,0x07,0x7c,0x7f,0x40,0x7f,
	0x00,0x00,0x00,0x00,0x80,0x80,0xc0,0xc0,0xe0,0xe0,0x60,0xe0,0x7e,0xfe,0x06,0xfe,
	0x20,0x3f,0x18,0x1f,0x08,0x0f,0x10,0x1f,0x33,0x3f,0x27,0x3f,0x3e,0x3e,0x1c,0x1c,
	0x0e,0xfe,0x3c,0xfc,0x38,0xf8,0x18,0xf8,0x9c,0xfc,0xcc,0xfc,0x7c,0x7c,0x3c,0x3c
};

const metasprite_t bbbbbr_stars_metasprite0[] = {
	METASPR_ITEM(48, 8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_TERM
};

const metasprite_t bbbbbr_stars_metasprite1[] = {
	METASPR_ITEM(48, 8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_TERM
};

const metasprite_t bbbbbr_stars_metasprite2[] = {
	METASPR_ITEM(32, 8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_ITEM(8, -8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_TERM
};

const metasprite_t bbbbbr_stars_metasprite3[] = {
	METASPR_ITEM(32, 8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_ITEM(8, -8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_TERM
};

const metasprite_t bbbbbr_stars_metasprite4[] = {
	METASPR_ITEM(32, 8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_ITEM(8, -8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_TERM
};

const metasprite_t bbbbbr_stars_metasprite5[] = {
	METASPR_ITEM(16, 8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_ITEM(8, -8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_ITEM(8, -8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_TERM
};

const metasprite_t bbbbbr_stars_metasprite6[] = {
	METASPR_ITEM(16, 8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_ITEM(8, -8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_ITEM(8, -8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_TERM
};

const metasprite_t bbbbbr_stars_metasprite7[] = {
	METASPR_ITEM(16, 8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(8, -8, 2, 0), METASPR_ITEM(0, 8, 3, 0), METASPR_ITEM(8, -8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_ITEM(8, -8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_TERM
};

const metasprite_t bbbbbr_stars_metasprite8[] = {
	METASPR_ITEM(16, 8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_ITEM(8, -8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_ITEM(8, -8, 4, 0), METASPR_ITEM(0, 8, 5, 0), METASPR_ITEM(8, -8, 6, 0), METASPR_ITEM(0, 8, 7, 0), METASPR_TERM
};

const metasprite_t* const bbbbbr_stars_metasprites[9] = {
	bbbbbr_stars_metasprite0, bbbbbr_stars_metasprite1, bbbbbr_stars_metasprite2, bbbbbr_stars_metasprite3, bbbbbr_stars_metasprite4, bbbbbr_stars_metasprite5, bbbbbr_stars_metasprite6, bbbbbr_stars_metasprite7, bbbbbr_stars_metasprite8
};
