//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bbbbbr_singlestar_H
#define METASPRITE_bbbbbr_singlestar_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bbbbbr_singlestar_TILE_ORIGIN 0
#define bbbbbr_singlestar_TILE_H 8
#define bbbbbr_singlestar_WIDTH 16
#define bbbbbr_singlestar_HEIGHT 16
#define bbbbbr_singlestar_TILE_COUNT 8
#define bbbbbr_singlestar_PIVOT_X -8
#define bbbbbr_singlestar_PIVOT_Y -16
#define bbbbbr_singlestar_PIVOT_W 16
#define bbbbbr_singlestar_PIVOT_H 16

BANKREF_EXTERN(bbbbbr_singlestar)

extern const palette_color_t bbbbbr_singlestar_palettes[4];
extern const uint8_t bbbbbr_singlestar_tiles[128];

extern const metasprite_t* const bbbbbr_singlestar_metasprites[2];

#endif