//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bbbbbr_bomb_H
#define METASPRITE_bbbbbr_bomb_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bbbbbr_bomb_TILE_ORIGIN 0
#define bbbbbr_bomb_TILE_H 8
#define bbbbbr_bomb_WIDTH 16
#define bbbbbr_bomb_HEIGHT 16
#define bbbbbr_bomb_TILE_COUNT 8
#define bbbbbr_bomb_PIVOT_X -8
#define bbbbbr_bomb_PIVOT_Y -16
#define bbbbbr_bomb_PIVOT_W 16
#define bbbbbr_bomb_PIVOT_H 16

BANKREF_EXTERN(bbbbbr_bomb)

extern const palette_color_t bbbbbr_bomb_palettes[4];
extern const uint8_t bbbbbr_bomb_tiles[128];

extern const metasprite_t* const bbbbbr_bomb_metasprites[2];

#endif