//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bbbbbr_getstars_player_H
#define METASPRITE_bbbbbr_getstars_player_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bbbbbr_getstars_player_TILE_ORIGIN 0
#define bbbbbr_getstars_player_TILE_H 8
#define bbbbbr_getstars_player_WIDTH 24
#define bbbbbr_getstars_player_HEIGHT 32
#define bbbbbr_getstars_player_TILE_COUNT 12
#define bbbbbr_getstars_player_PIVOT_X -8
#define bbbbbr_getstars_player_PIVOT_Y -16
#define bbbbbr_getstars_player_PIVOT_W 10
#define bbbbbr_getstars_player_PIVOT_H 28

BANKREF_EXTERN(bbbbbr_getstars_player)

extern const palette_color_t bbbbbr_getstars_player_palettes[4];
extern const uint8_t bbbbbr_getstars_player_tiles[192];

extern const metasprite_t* const bbbbbr_getstars_player_metasprites[3];

#endif