//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bbbbbr_stars_H
#define METASPRITE_bbbbbr_stars_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bbbbbr_stars_TILE_ORIGIN 0
#define bbbbbr_stars_TILE_H 8
#define bbbbbr_stars_WIDTH 16
#define bbbbbr_stars_HEIGHT 48
#define bbbbbr_stars_TILE_COUNT 8
#define bbbbbr_stars_PIVOT_X -8
#define bbbbbr_stars_PIVOT_Y -16
#define bbbbbr_stars_PIVOT_W 16
#define bbbbbr_stars_PIVOT_H 48

BANKREF_EXTERN(bbbbbr_stars)

extern const palette_color_t bbbbbr_stars_palettes[4];
extern const uint8_t bbbbbr_stars_tiles[128];

extern const metasprite_t* const bbbbbr_stars_metasprites[9];

#endif