//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineCartArts_H
#define METASPRITE_engineCartArts_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineCartArts_TILE_ORIGIN 64
#define engineCartArts_TILE_W 8
#define engineCartArts_TILE_H 8
#define engineCartArts_WIDTH 16
#define engineCartArts_HEIGHT 16
#define engineCartArts_TILE_COUNT 80
#define engineCartArts_PALETTE_COUNT 1
#define engineCartArts_COLORS_PER_PALETTE 4
#define engineCartArts_TOTAL_COLORS 4
#define engineCartArts_MAP_ATTRIBUTES 0

BANKREF_EXTERN(engineCartArts)

extern const palette_color_t engineCartArts_palettes[4];
extern const uint8_t engineCartArts_tiles[1280];

extern const unsigned char engineCartArts_map[80];

#endif
