//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineCartArts_H
#define METASPRITE_engineCartArts_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineCartArts_TILE_ORIGIN 64
#define engineCartArts_TILE_H 8
#define engineCartArts_WIDTH 16
#define engineCartArts_HEIGHT 16
#define engineCartArts_TILE_COUNT 79
#define engineCartArts_MAP_ATTRIBUTES 0
#define engineCartArts_TILE_PALS engineCartArts_tile_pals

BANKREF_EXTERN(engineCartArts)

extern const palette_color_t engineCartArts_palettes[4];
extern const uint8_t engineCartArts_tiles[1264];

extern const unsigned char engineCartArts_map[80];
extern const unsigned char* engineCartArts_tile_pals[79];

#endif