//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineWordRemix_H
#define METASPRITE_engineWordRemix_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineWordRemix_TILE_ORIGIN 144
#define engineWordRemix_TILE_W 8
#define engineWordRemix_TILE_H 8
#define engineWordRemix_WIDTH 8
#define engineWordRemix_HEIGHT 8
#define engineWordRemix_TILE_COUNT 40
#define engineWordRemix_PALETTE_COUNT 1
#define engineWordRemix_COLORS_PER_PALETTE 4
#define engineWordRemix_TOTAL_COLORS 4
#define engineWordRemix_MAP_ATTRIBUTES 0

BANKREF_EXTERN(engineWordRemix)

extern const palette_color_t engineWordRemix_palettes[4];
extern const uint8_t engineWordRemix_tiles[640];

extern const unsigned char engineWordRemix_map[40];

#endif
