//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineABWordRemix_H
#define METASPRITE_engineABWordRemix_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineABWordRemix_TILE_ORIGIN 80
#define engineABWordRemix_TILE_W 8
#define engineABWordRemix_TILE_H 8
#define engineABWordRemix_WIDTH 8
#define engineABWordRemix_HEIGHT 16
#define engineABWordRemix_TILE_COUNT 40
#define engineABWordRemix_PALETTE_COUNT 1
#define engineABWordRemix_COLORS_PER_PALETTE 4
#define engineABWordRemix_TOTAL_COLORS 4
#define engineABWordRemix_MAP_ATTRIBUTES 0

BANKREF_EXTERN(engineABWordRemix)

extern const palette_color_t engineABWordRemix_palettes[4];
extern const uint8_t engineABWordRemix_tiles[640];

extern const unsigned char engineABWordRemix_map[40];

#endif
