//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineWordCredits_H
#define METASPRITE_engineWordCredits_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineWordCredits_TILE_ORIGIN 128
#define engineWordCredits_TILE_W 8
#define engineWordCredits_TILE_H 8
#define engineWordCredits_WIDTH 8
#define engineWordCredits_HEIGHT 16
#define engineWordCredits_TILE_COUNT 48
#define engineWordCredits_PALETTE_COUNT 1
#define engineWordCredits_COLORS_PER_PALETTE 4
#define engineWordCredits_TOTAL_COLORS 4
#define engineWordCredits_MAP_ATTRIBUTES 0

BANKREF_EXTERN(engineWordCredits)

extern const palette_color_t engineWordCredits_palettes[4];
extern const uint8_t engineWordCredits_tiles[768];

extern const unsigned char engineWordCredits_map[48];

#endif
