//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineTitleLogo_H
#define METASPRITE_engineTitleLogo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineTitleLogo_TILE_ORIGIN 48
#define engineTitleLogo_TILE_W 8
#define engineTitleLogo_TILE_H 8
#define engineTitleLogo_WIDTH 8
#define engineTitleLogo_HEIGHT 16
#define engineTitleLogo_TILE_COUNT 86
#define engineTitleLogo_PALETTE_COUNT 1
#define engineTitleLogo_COLORS_PER_PALETTE 4
#define engineTitleLogo_TOTAL_COLORS 4
#define engineTitleLogo_MAP_ATTRIBUTES 0

BANKREF_EXTERN(engineTitleLogo)

extern const palette_color_t engineTitleLogo_palettes[4];
extern const uint8_t engineTitleLogo_tiles[1376];

extern const unsigned char engineTitleLogo_map[126];

#endif
