//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineWordPlay_H
#define METASPRITE_engineWordPlay_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineWordPlay_TILE_ORIGIN 48
#define engineWordPlay_TILE_W 8
#define engineWordPlay_TILE_H 8
#define engineWordPlay_WIDTH 8
#define engineWordPlay_HEIGHT 16
#define engineWordPlay_TILE_COUNT 30
#define engineWordPlay_PALETTE_COUNT 1
#define engineWordPlay_COLORS_PER_PALETTE 4
#define engineWordPlay_TOTAL_COLORS 4
#define engineWordPlay_MAP_ATTRIBUTES 0

BANKREF_EXTERN(engineWordPlay)

extern const palette_color_t engineWordPlay_palettes[4];
extern const uint8_t engineWordPlay_tiles[480];

extern const unsigned char engineWordPlay_map[32];

#endif
