//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineTitleCornerGarnish_H
#define METASPRITE_engineTitleCornerGarnish_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineTitleCornerGarnish_TILE_ORIGIN 0
#define engineTitleCornerGarnish_TILE_W 8
#define engineTitleCornerGarnish_TILE_H 8
#define engineTitleCornerGarnish_WIDTH 32
#define engineTitleCornerGarnish_HEIGHT 32
#define engineTitleCornerGarnish_TILE_COUNT 5
#define engineTitleCornerGarnish_PALETTE_COUNT 1
#define engineTitleCornerGarnish_COLORS_PER_PALETTE 4
#define engineTitleCornerGarnish_TOTAL_COLORS 4
#define engineTitleCornerGarnish_PIVOT_X 0
#define engineTitleCornerGarnish_PIVOT_Y 0
#define engineTitleCornerGarnish_PIVOT_W 32
#define engineTitleCornerGarnish_PIVOT_H 32

BANKREF_EXTERN(engineTitleCornerGarnish)

extern const palette_color_t engineTitleCornerGarnish_palettes[4];
extern const uint8_t engineTitleCornerGarnish_tiles[80];

extern const metasprite_t* const engineTitleCornerGarnish_metasprites[1];

#endif
