//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineGBCart_H
#define METASPRITE_engineGBCart_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineGBCart_TILE_ORIGIN 64
#define engineGBCart_TILE_W 8
#define engineGBCart_TILE_H 8
#define engineGBCart_WIDTH 8
#define engineGBCart_HEIGHT 8
#define engineGBCart_TILE_COUNT 70
#define engineGBCart_PALETTE_COUNT 1
#define engineGBCart_COLORS_PER_PALETTE 4
#define engineGBCart_TOTAL_COLORS 4
#define engineGBCart_MAP_ATTRIBUTES 0

BANKREF_EXTERN(engineGBCart)

extern const palette_color_t engineGBCart_palettes[4];
extern const uint8_t engineGBCart_tiles[1120];

extern const unsigned char engineGBCart_map[288];

#endif
