//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineDMGBezel_H
#define METASPRITE_engineDMGBezel_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineDMGBezel_TILE_ORIGIN 144
#define engineDMGBezel_TILE_H 8
#define engineDMGBezel_WIDTH 8
#define engineDMGBezel_HEIGHT 8
#define engineDMGBezel_TILE_COUNT 19
#define engineDMGBezel_MAP_ATTRIBUTES 0
#define engineDMGBezel_TILE_PALS engineDMGBezel_tile_pals

BANKREF_EXTERN(engineDMGBezel)

extern const palette_color_t engineDMGBezel_palettes[4];
extern const uint8_t engineDMGBezel_tiles[304];

extern const unsigned char engineDMGBezel_map[360];
extern const unsigned char* engineDMGBezel_tile_pals[19];

#endif