//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineABWordPlay_H
#define METASPRITE_engineABWordPlay_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineABWordPlay_TILE_ORIGIN 48
#define engineABWordPlay_TILE_W 8
#define engineABWordPlay_TILE_H 8
#define engineABWordPlay_WIDTH 8
#define engineABWordPlay_HEIGHT 16
#define engineABWordPlay_TILE_COUNT 32
#define engineABWordPlay_PALETTE_COUNT 1
#define engineABWordPlay_COLORS_PER_PALETTE 4
#define engineABWordPlay_TOTAL_COLORS 4
#define engineABWordPlay_MAP_ATTRIBUTES 0

BANKREF_EXTERN(engineABWordPlay)

extern const palette_color_t engineABWordPlay_palettes[4];
extern const uint8_t engineABWordPlay_tiles[512];

extern const unsigned char engineABWordPlay_map[32];

#endif
