//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_engineABWordCredits_H
#define METASPRITE_engineABWordCredits_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define engineABWordCredits_TILE_ORIGIN 128
#define engineABWordCredits_TILE_W 8
#define engineABWordCredits_TILE_H 8
#define engineABWordCredits_WIDTH 8
#define engineABWordCredits_HEIGHT 16
#define engineABWordCredits_TILE_COUNT 48
#define engineABWordCredits_PALETTE_COUNT 1
#define engineABWordCredits_COLORS_PER_PALETTE 4
#define engineABWordCredits_TOTAL_COLORS 4
#define engineABWordCredits_MAP_ATTRIBUTES 0

BANKREF_EXTERN(engineABWordCredits)

extern const palette_color_t engineABWordCredits_palettes[4];
extern const uint8_t engineABWordCredits_tiles[768];

extern const unsigned char engineABWordCredits_map[48];

#endif
