/*

 OSHFHBMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 10
   Map size      : 20 x 18
   Tile set      : C:\gbdk\GBMicroGames-master\oshf\res\raw tiles\oshfHBTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __oshfHBMap_h_INCLUDE
#define __oshfHBMap_h_INCLUDE

#define oshfHBMapWidth 20
#define oshfHBMapHeight 18
#define oshfHBMapBank 10

extern const void __bank_oshfHBMap;
extern const unsigned char oshfHBMap[];

#endif

/* End of OSHFHBMAP.H */
