/*

 OSHFRPSS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 10
   Map size      : 2 x 2
   Tile set      : C:\gbdk\GBMicroGames-master\oshf\res\raw tiles\oshfRPSBGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __oshfRPSS_h_INCLUDE
#define __oshfRPSS_h_INCLUDE

#define oshfRPSSWidth 2
#define oshfRPSSHeight 2
#define oshfRPSSBank 10

extern const void __bank_oshfRPSS;
extern const unsigned char oshfRPSS[];

#endif

/* End of OSHFRPSS.H */
