#pragma bank 10

/*

 OSHFRPSS.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 10
   Map size      : 2 x 2
   Tile set      : C:\gbdk\GBMicroGames-master\oshf\res\raw tiles\oshfRPSBGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define oshfRPSSWidth 2
#define oshfRPSSHeight 2
#define oshfRPSSBank 10

const void __at(10) __bank_oshfRPSS;
const unsigned char oshfRPSS[] =
{
  0x34,0x35,0x36,0x37
};

/* End of OSHFRPSS.C */
