/*

 OSHFRPSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 10
   Map size      : 20 x 18
   Tile set      : C:\gbdk\GBMicroGames-master\oshf\res\raw tiles\oshfRPSBGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __oshfRPSMap_h_INCLUDE
#define __oshfRPSMap_h_INCLUDE

#define oshfRPSMapWidth 20
#define oshfRPSMapHeight 18
#define oshfRPSMapBank 10

extern const void __bank_oshfRPSMap;
extern const unsigned char oshfRPSMap[];

#endif

/* End of OSHFRPSMAP.H */
