/*

 OSHFRPSP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 10
   Map size      : 2 x 2
   Tile set      : C:\gbdk\GBMicroGames-master\oshf\res\raw tiles\oshfRPSBGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __oshfRPSP_h_INCLUDE
#define __oshfRPSP_h_INCLUDE

#define oshfRPSPWidth 2
#define oshfRPSPHeight 2
#define oshfRPSPBank 10

extern const void __bank_oshfRPSP;
extern const unsigned char oshfRPSP[];

#endif

/* End of OSHFRPSP.H */
