#pragma bank 10

/*

 OSHFRPSR.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 10
   Map size      : 2 x 2
   Tile set      : C:\gbdk\GBMicroGames-master\oshf\res\raw tiles\oshfRPSBGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define oshfRPSRWidth 2
#define oshfRPSRHeight 2
#define oshfRPSRBank 10

const void __at(10) __bank_oshfRPSR;
const unsigned char oshfRPSR[] =
{
  0x2C,0x2D,0x2E,0x2F
};

/* End of OSHFRPSR.C */
