/*

 OSHFRPSR.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 10
   Map size      : 2 x 2
   Tile set      : C:\gbdk\GBMicroGames-master\oshf\res\raw tiles\oshfRPSBGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __oshfRPSR_h_INCLUDE
#define __oshfRPSR_h_INCLUDE

#define oshfRPSRWidth 2
#define oshfRPSRHeight 2
#define oshfRPSRBank 10

extern const void __bank_oshfRPSR;
extern const unsigned char oshfRPSR[];

#endif

/* End of OSHFRPSR.H */
