#pragma bank 10

/*

 OSHFRPSP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 10
   Map size      : 2 x 2
   Tile set      : C:\gbdk\GBMicroGames-master\oshf\res\raw tiles\oshfRPSBGTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define oshfRPSPWidth 2
#define oshfRPSPHeight 2
#define oshfRPSPBank 10

const void __at(10) __bank_oshfRPSP;
const unsigned char oshfRPSP[] =
{
  0x30,0x31,0x32,0x33
};

/* End of OSHFRPSP.C */
