#ifdef MICROGAME
MICROGAME(MG_BOWNLY_BOW, bownlyBowMicrogameMain, 2U, 4U, "SHOOT", "SHOOT", "SHOOT")
MICROGAME(MG_BOWNLY_MAGIPANELS5, bownlyMP5MicrogameMain, 2U, 4U, "INCREASE TO 5", "INCREASE TO 5", "INCREASE TO 5")
MICROGAME(MG_BOWNLY_PASTEL, bownlyPastelMicrogameMain, 2U, 4U, "COLLECT HEARTS!", "COLLECT HEARTS!", "COLLECT HEARTS!")
MICROGAME(MG_TEMPLATE, sharedTemplateMicrogameMain, 2U, 5U, "MAKE A GAME!", "MAKE A GAME!", "MAKE A GAME!")
#endif
