#pragma bank 10

/*

 OSHFRPSARROW.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const void __at(10) __bank_oshfRPSArrow;
const unsigned char oshfRPSArrow[] =
{
  0x00,0x00,0x30,0x30,0x7F,0x5F,0xFF,0x81,
  0xFF,0x81,0x7F,0x5F,0x30,0x30,0x00,0x00,
  0x00,0x00,0x30,0x30,0x5F,0x7F,0x81,0xFF,
  0x81,0xFF,0x5F,0x7F,0x30,0x30,0x00,0x00
};

/* End of OSHFRPSARROW.C */
