/*

 OSHFHBTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 30

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __oshfHBTiles_h_INCLUDE
#define __oshfHBTiles_h_INCLUDE

/* Bank of tiles. */
#define oshfHBTilesBank 10
/* Start of tile array. */
extern const void __bank_oshfHBTiles;
extern const unsigned char oshfHBTiles[];

#endif

/* End of OSHFHBTILES.H */
