/*

 OSHFRPSCLOUD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : Yes.
  Index offset         : 0
  Index counter        : None.

 This file was generated by GBTD v2.2

*/

#ifndef __oshfRPSCloud_h_INCLUDE
#define __oshfRPSCloud_h_INCLUDE

/* Bank of tiles. */
#define oshfRPSCloudBank 10
/* Metatile index */
extern const void __bank_oshfRPSCloudIndex;
extern const unsigned char oshfRPSCloudIndex[];
/* Start of tile array. */
extern const void __bank_oshfRPSCloud;
extern const unsigned char oshfRPSCloud[];

#endif

/* End of OSHFRPSCLOUD.H */
