/*

 OSHFRPSLCLOUD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : Yes.
  Index offset         : 0
  Index counter        : None.

 This file was generated by GBTD v2.2

*/

#ifndef __oshfRPSLCloud_h_INCLUDE
#define __oshfRPSLCloud_h_INCLUDE

/* Bank of tiles. */
#define oshfRPSLCloudBank 10
/* Metatile index */
extern const void __bank_oshfRPSLCloudIndex;
extern const unsigned char oshfRPSLCloudIndex[];
/* Start of tile array. */
extern const void __bank_oshfRPSLCloud;
extern const unsigned char oshfRPSLCloud[];

#endif

/* End of OSHFRPSLCLOUD.H */
