/*

 OSHFRPSNINJAR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : Yes.
  Index offset         : 0
  Index counter        : None.

 This file was generated by GBTD v2.2

*/

#ifndef __oshfRPSNinjaR_h_INCLUDE
#define __oshfRPSNinjaR_h_INCLUDE

/* Bank of tiles. */
#define oshfRPSNinjaRBank 10
/* Metatile index */
extern const void __bank_oshfRPSNinjaRIndex;
extern const unsigned char oshfRPSNinjaRIndex[];
/* Start of tile array. */
extern const void __bank_oshfRPSNinjaR;
extern const unsigned char oshfRPSNinjaR[];

#endif

/* End of OSHFRPSNINJAR.H */
