/*

 OSHFRPSNINJAP.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : Yes.
  Index offset         : 0
  Index counter        : None.

 This file was generated by GBTD v2.2

*/

#ifndef __oshfRPSNinjaP_h_INCLUDE
#define __oshfRPSNinjaP_h_INCLUDE

/* Bank of tiles. */
#define oshfRPSNinjaPBank 10
/* Metatile index */
extern const void __bank_oshfRPSNinjaPIndex;
extern const unsigned char oshfRPSNinjaPIndex[];
/* Start of tile array. */
extern const void __bank_oshfRPSNinjaP;
extern const unsigned char oshfRPSNinjaP[];

#endif

/* End of OSHFRPSNINJAP.H */
