/*

 BOWNLYPASTELTREEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 10
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyPastelTreeTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyPastelTreeMap_h_INCLUDE
#define __bownlyPastelTreeMap_h_INCLUDE

#define bownlyPastelTreeMapWidth 6
#define bownlyPastelTreeMapHeight 10
#define bownlyPastelTreeMapBank 0

extern const unsigned char bownlyPastelTreeMap[];

#endif

/* End of BOWNLYPASTELTREEMAP.H */
