/*

 BOWNLYBERONSTALKDOWNMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 9
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyBeronMushTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bownlyBeronStalkDownMapWidth 2
#define bownlyBeronStalkDownMapHeight 9
#define bownlyBeronStalkDownMapBank 0

const unsigned char bownlyBeronStalkDownMap[] =
{
  0x60,0x61,0x5E,0x5F,0x5C,0x5D,0x5A,0x5B,0x60,0x61,
  0x5E,0x5F,0x5C,0x5D,0x5A,0x5B,0x58,0x59
};

/* End of BOWNLYBERONSTALKDOWNMAP.C */
