/*

 BOWNLYPASTELBKG3MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 11
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyPastelBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 63
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyPastelBkg3Map_h_INCLUDE
#define __bownlyPastelBkg3Map_h_INCLUDE

#define bownlyPastelBkg3MapWidth 20
#define bownlyPastelBkg3MapHeight 11
#define bownlyPastelBkg3MapBank 0

extern const unsigned char bownlyPastelBkg3Map[];

#endif

/* End of BOWNLYPASTELBKG3MAP.H */
