/*

 BOWNLYBERONSTALKUPMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 9
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyBeronMushTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bownlyBeronStalkUpMapWidth 2
#define bownlyBeronStalkUpMapHeight 9
#define bownlyBeronStalkUpMapBank 0

const unsigned char bownlyBeronStalkUpMap[] =
{
  0x3F,0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,
  0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48
};

/* End of BOWNLYBERONSTALKUPMAP.C */
