/*

 BOWNLYPASTELBKG2MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 8
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyPastelBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 63
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyPastelBkg2Map_h_INCLUDE
#define __bownlyPastelBkg2Map_h_INCLUDE

#define bownlyPastelBkg2MapWidth 20
#define bownlyPastelBkg2MapHeight 8
#define bownlyPastelBkg2MapBank 0

extern const unsigned char bownlyPastelBkg2Map[];

#endif

/* End of BOWNLYPASTELBKG2MAP.H */
