/*

 BOWNLYPASTELBKG3MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 6
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyPastelBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 63
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bownlyPastelBkg3MapWidth 4
#define bownlyPastelBkg3MapHeight 6
#define bownlyPastelBkg3MapBank 0

const unsigned char bownlyPastelBkg3Map[] =
{
  0x40,0x46,0x41,0x49,0x4B,0x3F,0x3F,0x51,0x4C,0x3F,
  0x3F,0x52,0x4C,0x3F,0x3F,0x53,0x4D,0x3F,0x3F,0x54,
  0x4E,0x3F,0x3F,0x55
};

/* End of BOWNLYPASTELBKG3MAP.C */
