/*

 BOWNLYPASTELBKG1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 5
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyPastelBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 63
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyPastelBkg1Map_h_INCLUDE
#define __bownlyPastelBkg1Map_h_INCLUDE

#define bownlyPastelBkg1MapWidth 20
#define bownlyPastelBkg1MapHeight 5
#define bownlyPastelBkg1MapBank 0

extern const unsigned char bownlyPastelBkg1Map[];

#endif

/* End of BOWNLYPASTELBKG1MAP.H */
