/*

 BOWNLYMP5STAGETOPMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : C:\Projects\Gameboy\Gameboy tile editor\bgborderTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 64
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyMP5StageTopMap_h_INCLUDE
#define __bownlyMP5StageTopMap_h_INCLUDE

#define bownlyMP5StageTopMapWidth 20
#define bownlyMP5StageTopMapHeight 2
#define bownlyMP5StageTopMapBank 0

extern const unsigned char bownlyMP5StageTopMap[];

#endif

/* End of BOWNLYMP5STAGETOPMAP.H */
