/*

 BOWNLYPASTELCLOUD1MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 3
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyPastelBkg2Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 63
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bownlyPastelCloud1MapWidth 10
#define bownlyPastelCloud1MapHeight 3
#define bownlyPastelCloud1MapBank 0

const unsigned char bownlyPastelCloud1Map[] =
{
  0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x49,
  0x4A,0x4B,0x4C,0x4D,0x4E,0x4F,0x50,0x51,0x52,0x53,
  0x54,0x55,0x3F,0x3F,0x3F,0x3F,0x3F,0x3F,0x54,0x55
};

/* End of BOWNLYPASTELCLOUD1MAP.C */
