/*

 BOWNLYMP5STAGECOLMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 14
   Tile set      : C:\Projects\Gameboy\Gameboy tile editor\bgborderTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 64
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyMP5StageColMap_h_INCLUDE
#define __bownlyMP5StageColMap_h_INCLUDE

#define bownlyMP5StageColMapWidth 2
#define bownlyMP5StageColMapHeight 14
#define bownlyMP5StageColMapBank 0

extern const unsigned char bownlyMP5StageColMap[];

#endif

/* End of BOWNLYMP5STAGECOLMAP.H */
