/*

 BOWNLYBERONCAPDOWNMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 3
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyBeronMushTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyBeronCapDownMap_h_INCLUDE
#define __bownlyBeronCapDownMap_h_INCLUDE

#define bownlyBeronCapDownMapWidth 6
#define bownlyBeronCapDownMapHeight 3
#define bownlyBeronCapDownMapBank 0

extern const unsigned char bownlyBeronCapDownMap[];

#endif

/* End of BOWNLYBERONCAPDOWNMAP.H */
