/*

 BOWNLYBERONCAPUPMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 3
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyBeronMushTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyBeronCapUpMap_h_INCLUDE
#define __bownlyBeronCapUpMap_h_INCLUDE

#define bownlyBeronCapUpMapWidth 6
#define bownlyBeronCapUpMapHeight 3
#define bownlyBeronCapUpMapBank 0

extern const unsigned char bownlyBeronCapUpMap[];

#endif

/* End of BOWNLYBERONCAPUPMAP.H */
