/*

 BOWNLYBERONSTALKUPMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 9
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyBeronMushTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyBeronStalkUpMap_h_INCLUDE
#define __bownlyBeronStalkUpMap_h_INCLUDE

#define bownlyBeronStalkUpMapWidth 2
#define bownlyBeronStalkUpMapHeight 9
#define bownlyBeronStalkUpMapBank 0

extern const unsigned char bownlyBeronStalkUpMap[];

#endif

/* End of BOWNLYBERONSTALKUPMAP.H */
