/*

 BOWNLYPASTELCLOUD1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 3
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Bownly\res\raw tiles\bownlyPastelBkg2Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 63
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bownlyPastelCloud1Map_h_INCLUDE
#define __bownlyPastelCloud1Map_h_INCLUDE

#define bownlyPastelCloud1MapWidth 10
#define bownlyPastelCloud1MapHeight 3
#define bownlyPastelCloud1MapBank 0

extern const unsigned char bownlyPastelCloud1Map[];

#endif

/* End of BOWNLYPASTELCLOUD1MAP.H */
