/*

 SYNCHINGFEELINGGHOSTMAPS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 11
   Map size      : 8 x 14
   Tile set      : C:\Users\MattP\Documents\GBDK\GBMicroGames-master\SynchingFeeling\res\raw tiles\synchingFeelingGhostTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __synchingFeelingGhostMaps_h_INCLUDE
#define __synchingFeelingGhostMaps_h_INCLUDE

#define synchingFeelingGhostMapsWidth 8
#define synchingFeelingGhostMapsHeight 14
#define synchingFeelingGhostMapsBank 11

extern const void __bank_synchingFeelingGhostMaps;
extern const unsigned char synchingFeelingGhostMaps[];

#endif

/* End of SYNCHINGFEELINGGHOSTMAPS.H */
