#pragma bank 11

/*

 SYNCHINGFEELINGEGGMAPS.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 11
   Map size      : 4 x 4
   Tile set      : C:\Users\MattP\Documents\GBDK\GBMicroGames-master\SynchingFeeling\res\raw tiles\synchingFeelingEggTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define synchingFeelingEggMapsWidth 4
#define synchingFeelingEggMapsHeight 4
#define synchingFeelingEggMapsBank 11

const void __at(11) __bank_synchingFeelingEggMaps;
const unsigned char synchingFeelingEggMaps[] =
{
  0x34,0x3A,0x35,0x32,0x31,0x3B,0x39,0x33,0x31,0x3B,
  0x39,0x33,0x36,0x3C,0x39,0x37
};

/* End of SYNCHINGFEELINGEGGMAPS.C */
