/*

 SYNCHINGFEELINGEGGMAPS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 11
   Map size      : 4 x 4
   Tile set      : C:\Users\MattP\Documents\GBDK\GBMicroGames-master\SynchingFeeling\res\raw tiles\synchingFeelingEggTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __synchingFeelingEggMaps_h_INCLUDE
#define __synchingFeelingEggMaps_h_INCLUDE

#define synchingFeelingEggMapsWidth 4
#define synchingFeelingEggMapsHeight 4
#define synchingFeelingEggMapsBank 11

extern const void __bank_synchingFeelingEggMaps;
extern const unsigned char synchingFeelingEggMaps[];

#endif

/* End of SYNCHINGFEELINGEGGMAPS.H */
