/*

 BOWNLYTIRETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __bownlyTireTiles_h_INCLUDE
#define __bownlyTireTiles_h_INCLUDE

/* Bank of tiles. */
#define bownlyTireTilesBank 0
/* Start of tile array. */
extern const unsigned char bownlyTireTiles[];

#endif

/* End of BOWNLYTIRETILES.H */
