/*

 BOWNLYBERONCROWNTILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char bownlyBeronCrownTiles[] =
{
  0x00,0x00,0x00,0x00,0x1C,0x1C,0x3E,0x32,
  0x7C,0x44,0x38,0x28,0x30,0x30,0x00,0x00
};

/* End of BOWNLYBERONCROWNTILES.C */
