/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 11
   Map size      : 20 x 18
   Tile set      : C:\Users\Johnny\Documents\gb tools\GBTD\bgtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 64
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __JBackground_h_INCLUDE
#define __JBackground_h_INCLUDE

#define JBackgroundWidth 20
#define JBackgroundHeight 18
#define JBackgroundBank 11

extern const void __bank_JBackground;
extern const unsigned char JBackground[];

#endif

/* End of BACKGROUND.H */
