//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bbbbbr_getstars_map_H
#define METASPRITE_bbbbbr_getstars_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bbbbbr_getstars_map_TILE_ORIGIN 0
#define bbbbbr_getstars_map_TILE_H 8
#define bbbbbr_getstars_map_WIDTH 160
#define bbbbbr_getstars_map_HEIGHT 144
#define bbbbbr_getstars_map_TILE_COUNT 30
#define bbbbbr_getstars_map_MAP_ATTRIBUTES 0
#define bbbbbr_getstars_map_TILE_PALS bbbbbr_getstars_map_tile_pals

BANKREF_EXTERN(bbbbbr_getstars_map)

extern const palette_color_t bbbbbr_getstars_map_palettes[4];
extern const uint8_t bbbbbr_getstars_map_tiles[480];

extern const unsigned char bbbbbr_getstars_map_map[360];
extern const unsigned char* bbbbbr_getstars_map_tile_pals[30];

#endif