/*

 TEMPLATEFACE2MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 2 x 2
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Template\res\raw tiles\templateFaceTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 64
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __templateFace2Map_h_INCLUDE
#define __templateFace2Map_h_INCLUDE

#define templateFace2MapWidth 2
#define templateFace2MapHeight 2
#define templateFace2MapBank 1

extern const void __bank_templateFace2Map;
extern const unsigned char templateFace2Map[];

#endif

/* End of TEMPLATEFACE2MAP.H */
