#pragma bank 1

/*

 TEMPLATEFACE1MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 2 x 2
   Tile set      : C:\Projects\Gameboy\GBMicroGames\Template\res\raw tiles\templateFaceTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 64
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define templateFace1MapWidth 2
#define templateFace1MapHeight 2
#define templateFace1MapBank 1

const void __at(1) __bank_templateFace1Map;
const unsigned char templateFace1Map[] =
{
  0x40,0x42,0x41,0x43
};

/* End of TEMPLATEFACE1MAP.C */
