/*

 WHACKMOLESBG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 8
   Map size      : 20 x 18
   Tile set      : MicroGameBGgraphics.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __whackMolesBG_h_INCLUDE
#define __whackMolesBG_h_INCLUDE

#define whackMolesBGWidth 20
#define whackMolesBGHeight 18
#define whackMolesBGBank 8

#define whackMolesBG whackMolesBGPLN0
extern const void __bank_whackMolesBGPLN0;
extern const unsigned char whackMolesBGPLN0[];

#endif

/* End of WHACKMOLESBG.H */
