/*

 WHACKMOLESPRITEGRAPHICS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 35

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __WhackMoleSpriteGraphics_h_INCLUDE
#define __WhackMoleSpriteGraphics_h_INCLUDE

/* Bank of tiles. */
#define WMSpriteGraphicsBank 8
/* Start of tile array. */
extern const void __bank_WMSpriteGraphics;
extern const unsigned char WMSpriteGraphics[];

#endif

/* End of WHACKMOLESPRITEGRAPHICS.H */
