//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dovesamButtons_H
#define METASPRITE_dovesamButtons_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dovesamButtons_TILE_ORIGIN 0
#define dovesamButtons_TILE_W 8
#define dovesamButtons_TILE_H 8
#define dovesamButtons_WIDTH 32
#define dovesamButtons_HEIGHT 80
#define dovesamButtons_TILE_COUNT 40
#define dovesamButtons_PALETTE_COUNT 1
#define dovesamButtons_COLORS_PER_PALETTE 4
#define dovesamButtons_TOTAL_COLORS 4
#define dovesamButtons_MAP_ATTRIBUTES 0

BANKREF_EXTERN(dovesamButtons)

extern const palette_color_t dovesamButtons_palettes[4];
extern const uint8_t dovesamButtons_tiles[640];

extern const unsigned char dovesamButtons_map[40];

#endif
