#pragma bank 7

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(dovesamPaddleSprite)

const palette_color_t dovesamPaddleSprite_palettes[4] = {
	RGB8(255, 255, 255), RGB8(224, 248, 207), RGB8(134, 192, 108), RGB8(7, 24, 33)
};

const uint8_t dovesamPaddleSprite_tiles[32] = {
	0x00,0x00,0x00,0x00,0x7f,0x7f,0x70,0x4f,0x60,0x5f,0x60,0x5f,0x70,0x4f,0x7f,0x7f,
	0x00,0x00,0x00,0x00,0xff,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0xff,0xff
};

const metasprite_t dovesamPaddleSprite_metasprite0[] = {
	METASPR_ITEM(-4, -12, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(0, 8, 0, 32), METASPR_TERM
};

const metasprite_t* const dovesamPaddleSprite_metasprites[1] = {
	dovesamPaddleSprite_metasprite0
};
