#pragma bank 7

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(dovesamPaddleSpriteSheet)

const palette_color_t dovesamPaddleSpriteSheet_palettes[4] = {
	RGB8(255,255,255), RGB8(224,248,207), RGB8(134,192,108), RGB8(  7, 24, 33)
	
};

const uint8_t dovesamPaddleSpriteSheet_tiles[48] = {
	0x00,0x00,0x00,0x00,
	0x7f,0x7f,0x70,0x4f,
	0x60,0x5f,0x60,0x5f,
	0x70,0x4f,0x7f,0x7f,
	
0x00,0x00,0x00,0x00,
	0xff,0xff,0x00,0xff,
	0x00,0xff,0x00,0xff,
	0x00,0xff,0xff,0xff,
	
0x00,0x00,0x00,0x00,
	0x07,0x07,0x07,0x04,
	0x06,0x05,0x06,0x05,
	0x07,0x04,0x07,0x07
	
};

const metasprite_t dovesamPaddleSpriteSheet_metasprite0[] = {
	METASPR_ITEM(-4, -16, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(0, 8, 0, 32), METASPR_TERM
};

const metasprite_t dovesamPaddleSpriteSheet_metasprite1[] = {
	METASPR_ITEM(-4, -16, 2, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_ITEM(0, 8, 2, 32), METASPR_TERM
};

const metasprite_t dovesamPaddleSpriteSheet_metasprite2[] = {
	METASPR_ITEM(-4, -8, 0, 0), METASPR_ITEM(0, 8, 0, 32), METASPR_TERM
};

const metasprite_t* const dovesamPaddleSpriteSheet_metasprites[3] = {
	dovesamPaddleSpriteSheet_metasprite0, dovesamPaddleSpriteSheet_metasprite1, dovesamPaddleSpriteSheet_metasprite2
};
