//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dovesamPaddleSpriteSheet_H
#define METASPRITE_dovesamPaddleSpriteSheet_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dovesamPaddleSpriteSheet_TILE_ORIGIN 0
#define dovesamPaddleSpriteSheet_TILE_W 8
#define dovesamPaddleSpriteSheet_TILE_H 8
#define dovesamPaddleSpriteSheet_WIDTH 32
#define dovesamPaddleSpriteSheet_HEIGHT 8
#define dovesamPaddleSpriteSheet_TILE_COUNT 3
#define dovesamPaddleSpriteSheet_PALETTE_COUNT 1
#define dovesamPaddleSpriteSheet_COLORS_PER_PALETTE 4
#define dovesamPaddleSpriteSheet_TOTAL_COLORS 4
#define dovesamPaddleSpriteSheet_PIVOT_X 16
#define dovesamPaddleSpriteSheet_PIVOT_Y 4
#define dovesamPaddleSpriteSheet_PIVOT_W 32
#define dovesamPaddleSpriteSheet_PIVOT_H 8

BANKREF_EXTERN(dovesamPaddleSpriteSheet)

extern const palette_color_t dovesamPaddleSpriteSheet_palettes[4];
extern const uint8_t dovesamPaddleSpriteSheet_tiles[48];

extern const metasprite_t* const dovesamPaddleSpriteSheet_metasprites[3];

#endif
