//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dovesamBallSprite_H
#define METASPRITE_dovesamBallSprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dovesamBallSprite_TILE_ORIGIN 0
#define dovesamBallSprite_TILE_H 8
#define dovesamBallSprite_WIDTH 8
#define dovesamBallSprite_HEIGHT 8
#define dovesamBallSprite_TILE_COUNT 1
#define dovesamBallSprite_PIVOT_X 4
#define dovesamBallSprite_PIVOT_Y 4
#define dovesamBallSprite_PIVOT_W 8
#define dovesamBallSprite_PIVOT_H 8

BANKREF_EXTERN(dovesamBallSprite)

extern const palette_color_t dovesamBallSprite_palettes[4];
extern const uint8_t dovesamBallSprite_tiles[16];

extern const metasprite_t* const dovesamBallSprite_metasprites[1];

#endif