//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_synchingFeelingGhostSpr_H
#define METASPRITE_synchingFeelingGhostSpr_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define synchingFeelingGhostSpr_TILE_ORIGIN 0
#define synchingFeelingGhostSpr_TILE_W 8
#define synchingFeelingGhostSpr_TILE_H 8
#define synchingFeelingGhostSpr_WIDTH 16
#define synchingFeelingGhostSpr_HEIGHT 16
#define synchingFeelingGhostSpr_TILE_COUNT 25
#define synchingFeelingGhostSpr_PALETTE_COUNT 1
#define synchingFeelingGhostSpr_COLORS_PER_PALETTE 4
#define synchingFeelingGhostSpr_TOTAL_COLORS 4
#define synchingFeelingGhostSpr_PIVOT_X 8
#define synchingFeelingGhostSpr_PIVOT_Y 8
#define synchingFeelingGhostSpr_PIVOT_W 16
#define synchingFeelingGhostSpr_PIVOT_H 16

BANKREF_EXTERN(synchingFeelingGhostSpr)

extern const palette_color_t synchingFeelingGhostSpr_palettes[4];
extern const uint8_t synchingFeelingGhostSpr_tiles[400];

extern const metasprite_t* const synchingFeelingGhostSpr_metasprites[13];

#endif
