//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_synchingFeelingCoinSpr_H
#define METASPRITE_synchingFeelingCoinSpr_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define synchingFeelingCoinSpr_TILE_ORIGIN 0
#define synchingFeelingCoinSpr_TILE_H 8
#define synchingFeelingCoinSpr_WIDTH 16
#define synchingFeelingCoinSpr_HEIGHT 16
#define synchingFeelingCoinSpr_TILE_COUNT 8
#define synchingFeelingCoinSpr_PIVOT_X 8
#define synchingFeelingCoinSpr_PIVOT_Y 8
#define synchingFeelingCoinSpr_PIVOT_W 16
#define synchingFeelingCoinSpr_PIVOT_H 16

BANKREF_EXTERN(synchingFeelingCoinSpr)

extern const palette_color_t synchingFeelingCoinSpr_palettes[4];
extern const uint8_t synchingFeelingCoinSpr_tiles[128];

extern const metasprite_t* const synchingFeelingCoinSpr_metasprites[4];

#endif