//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_synchingFeelingEggSpr_H
#define METASPRITE_synchingFeelingEggSpr_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define synchingFeelingEggSpr_TILE_ORIGIN 0
#define synchingFeelingEggSpr_TILE_W 8
#define synchingFeelingEggSpr_TILE_H 8
#define synchingFeelingEggSpr_WIDTH 16
#define synchingFeelingEggSpr_HEIGHT 16
#define synchingFeelingEggSpr_TILE_COUNT 14
#define synchingFeelingEggSpr_PALETTE_COUNT 1
#define synchingFeelingEggSpr_COLORS_PER_PALETTE 4
#define synchingFeelingEggSpr_TOTAL_COLORS 4
#define synchingFeelingEggSpr_PIVOT_X 8
#define synchingFeelingEggSpr_PIVOT_Y 8
#define synchingFeelingEggSpr_PIVOT_W 16
#define synchingFeelingEggSpr_PIVOT_H 16

BANKREF_EXTERN(synchingFeelingEggSpr)

extern const palette_color_t synchingFeelingEggSpr_palettes[4];
extern const uint8_t synchingFeelingEggSpr_tiles[224];

extern const metasprite_t* const synchingFeelingEggSpr_metasprites[11];

#endif
