//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_synchingFeelingEyeSpr_H
#define METASPRITE_synchingFeelingEyeSpr_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define synchingFeelingEyeSpr_TILE_ORIGIN 0
#define synchingFeelingEyeSpr_TILE_W 8
#define synchingFeelingEyeSpr_TILE_H 8
#define synchingFeelingEyeSpr_WIDTH 16
#define synchingFeelingEyeSpr_HEIGHT 16
#define synchingFeelingEyeSpr_TILE_COUNT 14
#define synchingFeelingEyeSpr_PALETTE_COUNT 1
#define synchingFeelingEyeSpr_COLORS_PER_PALETTE 4
#define synchingFeelingEyeSpr_TOTAL_COLORS 4
#define synchingFeelingEyeSpr_PIVOT_X 8
#define synchingFeelingEyeSpr_PIVOT_Y 8
#define synchingFeelingEyeSpr_PIVOT_W 16
#define synchingFeelingEyeSpr_PIVOT_H 16

BANKREF_EXTERN(synchingFeelingEyeSpr)

extern const palette_color_t synchingFeelingEyeSpr_palettes[4];
extern const uint8_t synchingFeelingEyeSpr_tiles[224];

extern const metasprite_t* const synchingFeelingEyeSpr_metasprites[6];

#endif
