/*

 ALBHEDFONTTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 46

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __alBhedFontTiles_h_INCLUDE
#define __alBhedFontTiles_h_INCLUDE

/* Bank of tiles. */
#define alBhedFontTilesBank 0
/* Start of tile array. */
extern const unsigned char alBhedFontTiles[];

#endif

/* End of ALBHEDFONTTILES.H */
