/*

 ENGINEMIXBORDERTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __engineMixBorderTiles_h_INCLUDE
#define __engineMixBorderTiles_h_INCLUDE

/* Bank of tiles. */
#define engineMixBorderTilesBank 0
/* Start of tile array. */
extern const unsigned char engineMixBorderTiles[];

#endif

/* End of ENGINEMIXBORDERTILES.H */
