/*

 SYNCHINGFEELINGGHOSTTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 61

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __synchingFeelingGhostTiles_h_INCLUDE
#define __synchingFeelingGhostTiles_h_INCLUDE

/* Bank of tiles. */
#define synchingFeeGhostTileBank 11
/* Start of tile array. */
extern const void __bank_synchingFeeGhostTile;
extern const unsigned char synchingFeeGhostTile[];

#endif

/* End of SYNCHINGFEELINGGHOSTTILES.H */
