//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprLizard_H
#define METASPRITE_bownlySprLizard_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprLizard_TILE_ORIGIN 0
#define bownlySprLizard_TILE_H 8
#define bownlySprLizard_WIDTH 16
#define bownlySprLizard_HEIGHT 24
#define bownlySprLizard_TILE_COUNT 7
#define bownlySprLizard_PIVOT_X 8
#define bownlySprLizard_PIVOT_Y 12
#define bownlySprLizard_PIVOT_W 16
#define bownlySprLizard_PIVOT_H 24

BANKREF_EXTERN(bownlySprLizard)

extern const palette_color_t bownlySprLizard_palettes[4];
extern const uint8_t bownlySprLizard_tiles[112];

extern const metasprite_t* const bownlySprLizard_metasprites[2];

#endif