//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprThingy_H
#define METASPRITE_bownlySprThingy_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprThingy_TILE_ORIGIN 0
#define bownlySprThingy_TILE_H 8
#define bownlySprThingy_WIDTH 24
#define bownlySprThingy_HEIGHT 24
#define bownlySprThingy_TILE_COUNT 24
#define bownlySprThingy_PIVOT_X 12
#define bownlySprThingy_PIVOT_Y 0
#define bownlySprThingy_PIVOT_W 24
#define bownlySprThingy_PIVOT_H 24

BANKREF_EXTERN(bownlySprThingy)

extern const palette_color_t bownlySprThingy_palettes[4];
extern const uint8_t bownlySprThingy_tiles[384];

extern const metasprite_t* const bownlySprThingy_metasprites[3];

#endif