//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprPreston_H
#define METASPRITE_bownlySprPreston_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprPreston_TILE_ORIGIN 0
#define bownlySprPreston_TILE_W 8
#define bownlySprPreston_TILE_H 8
#define bownlySprPreston_WIDTH 16
#define bownlySprPreston_HEIGHT 16
#define bownlySprPreston_TILE_COUNT 52
#define bownlySprPreston_PALETTE_COUNT 1
#define bownlySprPreston_COLORS_PER_PALETTE 4
#define bownlySprPreston_TOTAL_COLORS 4
#define bownlySprPreston_PIVOT_X 0
#define bownlySprPreston_PIVOT_Y 0
#define bownlySprPreston_PIVOT_W 16
#define bownlySprPreston_PIVOT_H 16

BANKREF_EXTERN(bownlySprPreston)

extern const palette_color_t bownlySprPreston_palettes[4];
extern const uint8_t bownlySprPreston_tiles[832];

extern const metasprite_t* const bownlySprPreston_metasprites[14];

#endif
