//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprSophie_H
#define METASPRITE_bownlySprSophie_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprSophie_TILE_ORIGIN 0
#define bownlySprSophie_TILE_H 8
#define bownlySprSophie_WIDTH 24
#define bownlySprSophie_HEIGHT 24
#define bownlySprSophie_TILE_COUNT 32
#define bownlySprSophie_PIVOT_X 0
#define bownlySprSophie_PIVOT_Y 0
#define bownlySprSophie_PIVOT_W 24
#define bownlySprSophie_PIVOT_H 24

BANKREF_EXTERN(bownlySprSophie)

extern const palette_color_t bownlySprSophie_palettes[4];
extern const uint8_t bownlySprSophie_tiles[512];

extern const metasprite_t* const bownlySprSophie_metasprites[5];

#endif