//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprBanana_H
#define METASPRITE_bownlySprBanana_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprBanana_TILE_ORIGIN 0
#define bownlySprBanana_TILE_W 8
#define bownlySprBanana_TILE_H 8
#define bownlySprBanana_WIDTH 16
#define bownlySprBanana_HEIGHT 16
#define bownlySprBanana_TILE_COUNT 4
#define bownlySprBanana_PALETTE_COUNT 1
#define bownlySprBanana_COLORS_PER_PALETTE 4
#define bownlySprBanana_TOTAL_COLORS 4
#define bownlySprBanana_PIVOT_X 8
#define bownlySprBanana_PIVOT_Y 0
#define bownlySprBanana_PIVOT_W 16
#define bownlySprBanana_PIVOT_H 16

BANKREF_EXTERN(bownlySprBanana)

extern const palette_color_t bownlySprBanana_palettes[4];
extern const uint8_t bownlySprBanana_tiles[64];

extern const metasprite_t* const bownlySprBanana_metasprites[1];

#endif
