//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprRabbit_H
#define METASPRITE_bownlySprRabbit_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprRabbit_TILE_ORIGIN 48
#define bownlySprRabbit_TILE_H 8
#define bownlySprRabbit_WIDTH 32
#define bownlySprRabbit_HEIGHT 160
#define bownlySprRabbit_TILE_COUNT 62
#define bownlySprRabbit_MAP_ATTRIBUTES 0
#define bownlySprRabbit_TILE_PALS bownlySprRabbit_tile_pals

BANKREF_EXTERN(bownlySprRabbit)

extern const palette_color_t bownlySprRabbit_palettes[4];
extern const uint8_t bownlySprRabbit_tiles[992];

extern const unsigned char bownlySprRabbit_map[80];
extern const unsigned char* bownlySprRabbit_tile_pals[62];

#endif