//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprBee_H
#define METASPRITE_bownlySprBee_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprBee_TILE_ORIGIN 0
#define bownlySprBee_TILE_H 8
#define bownlySprBee_WIDTH 16
#define bownlySprBee_HEIGHT 16
#define bownlySprBee_TILE_COUNT 8
#define bownlySprBee_PIVOT_X 8
#define bownlySprBee_PIVOT_Y 0
#define bownlySprBee_PIVOT_W 16
#define bownlySprBee_PIVOT_H 16

BANKREF_EXTERN(bownlySprBee)

extern const palette_color_t bownlySprBee_palettes[4];
extern const uint8_t bownlySprBee_tiles[128];

extern const metasprite_t* const bownlySprBee_metasprites[2];

#endif