//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprBeron_H
#define METASPRITE_bownlySprBeron_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprBeron_TILE_ORIGIN 0
#define bownlySprBeron_TILE_W 8
#define bownlySprBeron_TILE_H 8
#define bownlySprBeron_WIDTH 16
#define bownlySprBeron_HEIGHT 16
#define bownlySprBeron_TILE_COUNT 28
#define bownlySprBeron_PALETTE_COUNT 1
#define bownlySprBeron_COLORS_PER_PALETTE 4
#define bownlySprBeron_TOTAL_COLORS 4
#define bownlySprBeron_PIVOT_X 0
#define bownlySprBeron_PIVOT_Y 0
#define bownlySprBeron_PIVOT_W 16
#define bownlySprBeron_PIVOT_H 16

BANKREF_EXTERN(bownlySprBeron)

extern const palette_color_t bownlySprBeron_palettes[4];
extern const uint8_t bownlySprBeron_tiles[448];

extern const metasprite_t* const bownlySprBeron_metasprites[7];

#endif
