//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlyBkgEarth_H
#define METASPRITE_bownlyBkgEarth_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlyBkgEarth_TILE_ORIGIN 48
#define bownlyBkgEarth_TILE_H 8
#define bownlyBkgEarth_WIDTH 104
#define bownlyBkgEarth_HEIGHT 104
#define bownlyBkgEarth_TILE_COUNT 92
#define bownlyBkgEarth_MAP_ATTRIBUTES 0
#define bownlyBkgEarth_TILE_PALS bownlyBkgEarth_tile_pals

BANKREF_EXTERN(bownlyBkgEarth)

extern const palette_color_t bownlyBkgEarth_palettes[4];
extern const uint8_t bownlyBkgEarth_tiles[1472];

extern const unsigned char bownlyBkgEarth_map[169];
extern const unsigned char* bownlyBkgEarth_tile_pals[92];

#endif