//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprArrow_H
#define METASPRITE_bownlySprArrow_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprArrow_TILE_ORIGIN 0
#define bownlySprArrow_TILE_W 8
#define bownlySprArrow_TILE_H 8
#define bownlySprArrow_WIDTH 32
#define bownlySprArrow_HEIGHT 8
#define bownlySprArrow_TILE_COUNT 3
#define bownlySprArrow_PALETTE_COUNT 1
#define bownlySprArrow_COLORS_PER_PALETTE 4
#define bownlySprArrow_TOTAL_COLORS 4
#define bownlySprArrow_PIVOT_X 16
#define bownlySprArrow_PIVOT_Y 4
#define bownlySprArrow_PIVOT_W 32
#define bownlySprArrow_PIVOT_H 8

BANKREF_EXTERN(bownlySprArrow)

extern const palette_color_t bownlySprArrow_palettes[4];
extern const uint8_t bownlySprArrow_tiles[48];

extern const metasprite_t* const bownlySprArrow_metasprites[1];

#endif
