//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprPastel_H
#define METASPRITE_bownlySprPastel_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprPastel_TILE_ORIGIN 0
#define bownlySprPastel_TILE_H 8
#define bownlySprPastel_WIDTH 32
#define bownlySprPastel_HEIGHT 32
#define bownlySprPastel_TILE_COUNT 86
#define bownlySprPastel_PIVOT_X 16
#define bownlySprPastel_PIVOT_Y 0
#define bownlySprPastel_PIVOT_W 32
#define bownlySprPastel_PIVOT_H 32

BANKREF_EXTERN(bownlySprPastel)

extern const palette_color_t bownlySprPastel_palettes[4];
extern const uint8_t bownlySprPastel_tiles[1376];

extern const metasprite_t* const bownlySprPastel_metasprites[16];

#endif