//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprJumppuff_H
#define METASPRITE_bownlySprJumppuff_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprJumppuff_TILE_ORIGIN 0
#define bownlySprJumppuff_TILE_H 8
#define bownlySprJumppuff_WIDTH 16
#define bownlySprJumppuff_HEIGHT 8
#define bownlySprJumppuff_TILE_COUNT 8
#define bownlySprJumppuff_PIVOT_X 8
#define bownlySprJumppuff_PIVOT_Y 0
#define bownlySprJumppuff_PIVOT_W 16
#define bownlySprJumppuff_PIVOT_H 8

BANKREF_EXTERN(bownlySprJumppuff)

extern const palette_color_t bownlySprJumppuff_palettes[4];
extern const uint8_t bownlySprJumppuff_tiles[128];

extern const metasprite_t* const bownlySprJumppuff_metasprites[8];

#endif