//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprDrill_H
#define METASPRITE_bownlySprDrill_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprDrill_TILE_ORIGIN 0
#define bownlySprDrill_TILE_H 8
#define bownlySprDrill_WIDTH 8
#define bownlySprDrill_HEIGHT 8
#define bownlySprDrill_TILE_COUNT 5
#define bownlySprDrill_PIVOT_X 0
#define bownlySprDrill_PIVOT_Y 0
#define bownlySprDrill_PIVOT_W 8
#define bownlySprDrill_PIVOT_H 8

BANKREF_EXTERN(bownlySprDrill)

extern const palette_color_t bownlySprDrill_palettes[4];
extern const uint8_t bownlySprDrill_tiles[80];

extern const metasprite_t* const bownlySprDrill_metasprites[5];

#endif