//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprBow_H
#define METASPRITE_bownlySprBow_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprBow_TILE_ORIGIN 0
#define bownlySprBow_TILE_W 8
#define bownlySprBow_TILE_H 8
#define bownlySprBow_WIDTH 24
#define bownlySprBow_HEIGHT 32
#define bownlySprBow_TILE_COUNT 14
#define bownlySprBow_PALETTE_COUNT 1
#define bownlySprBow_COLORS_PER_PALETTE 4
#define bownlySprBow_TOTAL_COLORS 4
#define bownlySprBow_PIVOT_X 12
#define bownlySprBow_PIVOT_Y 16
#define bownlySprBow_PIVOT_W 24
#define bownlySprBow_PIVOT_H 32

BANKREF_EXTERN(bownlySprBow)

extern const palette_color_t bownlySprBow_palettes[4];
extern const uint8_t bownlySprBow_tiles[224];

extern const metasprite_t* const bownlySprBow_metasprites[2];

#endif
