//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bownlySprCarrot_H
#define METASPRITE_bownlySprCarrot_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bownlySprCarrot_TILE_ORIGIN 160
#define bownlySprCarrot_TILE_W 8
#define bownlySprCarrot_TILE_H 8
#define bownlySprCarrot_WIDTH 24
#define bownlySprCarrot_HEIGHT 120
#define bownlySprCarrot_TILE_COUNT 15
#define bownlySprCarrot_PALETTE_COUNT 1
#define bownlySprCarrot_COLORS_PER_PALETTE 4
#define bownlySprCarrot_TOTAL_COLORS 4
#define bownlySprCarrot_MAP_ATTRIBUTES 0

BANKREF_EXTERN(bownlySprCarrot)

extern const palette_color_t bownlySprCarrot_palettes[4];
extern const uint8_t bownlySprCarrot_tiles[240];

extern const unsigned char bownlySprCarrot_map[45];

#endif
