//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprArrow_H
#define METASPRITE_sprArrow_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprArrow_TILE_ORIGIN 0
#define sprArrow_TILE_H 8
#define sprArrow_WIDTH 32
#define sprArrow_HEIGHT 8
#define sprArrow_TILE_COUNT 3
#define sprArrow_PIVOT_X 16
#define sprArrow_PIVOT_Y 4
#define sprArrow_PIVOT_W 32
#define sprArrow_PIVOT_H 8

BANKREF_EXTERN(sprArrow)

extern const palette_color_t sprArrow_palettes[4];
extern const uint8_t sprArrow_tiles[48];

extern const metasprite_t* const sprArrow_metasprites[1];

#endif