//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprBow_H
#define METASPRITE_sprBow_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprBow_TILE_ORIGIN 0
#define sprBow_TILE_H 8
#define sprBow_WIDTH 24
#define sprBow_HEIGHT 32
#define sprBow_TILE_COUNT 14
#define sprBow_PIVOT_X 12
#define sprBow_PIVOT_Y 16
#define sprBow_PIVOT_W 24
#define sprBow_PIVOT_H 32

BANKREF_EXTERN(sprBow)

extern const palette_color_t sprBow_palettes[4];
extern const uint8_t sprBow_tiles[224];

extern const metasprite_t* const sprBow_metasprites[2];

#endif