//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprTarget_H
#define METASPRITE_sprTarget_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprTarget_TILE_ORIGIN 0
#define sprTarget_TILE_H 8
#define sprTarget_WIDTH 24
#define sprTarget_HEIGHT 32
#define sprTarget_TILE_COUNT 6
#define sprTarget_PIVOT_X 12
#define sprTarget_PIVOT_Y 16
#define sprTarget_PIVOT_W 24
#define sprTarget_PIVOT_H 32

BANKREF_EXTERN(sprTarget)

extern const palette_color_t sprTarget_palettes[4];
extern const uint8_t sprTarget_tiles[96];

extern const metasprite_t* const sprTarget_metasprites[1];

#endif