/*

 aim.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __aim_h_INCLUDE
#define __aim_h_INCLUDE

/* Bank of tiles. */
#define aimBank 11
/* Start of tile array. */
extern const void __bank_aim;
extern const unsigned char aim[];

#endif

/* End of aim.H */
