#pragma bank 11

/*

 aim.c

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const void __at(11) __bank_aim;
const unsigned char aim[] =
{
  0x3C,0x3C,0x42,0x42,0xA5,0xA5,0x99,0x99,
  0x99,0x99,0xA5,0xA5,0x42,0x42,0x3C,0x3C
};

/* End of aim.C */
