/*

 THUMBSUP.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ThumbsUp_h_INCLUDE
#define __ThumbsUp_h_INCLUDE

/* Bank of tiles. */
#define ThumbsUpBank 11
/* Start of tile array. */
extern const void __bank_ThumbsUp;
extern const unsigned char ThumbsUp[];

#endif

/* End of THUMBSUP.H */
