/*

 UI.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char Ui[] =
{
  0x38,0x38,0x7D,0x7D,0x7E,0x7E,0x7C,0x28,
  0xFE,0x28,0xBA,0x44,0x7C,0x38,0x38,0x00,
  0x70,0x70,0x88,0xC8,0xA8,0xC8,0xA8,0xC8,
  0xA8,0xC8,0x50,0x70,0xA8,0xC8,0xF8,0xF8
};

/* End of UI.C */
