/*

 ADRIANJGHITTHENOTETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 6

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __adrianJGHitTheNoteTiles_h_INCLUDE
#define __adrianJGHitTheNoteTiles_h_INCLUDE

/* Start of tile array. */
extern const unsigned char adrianJGHitTheNoteTiles[];

#endif

/* End of ADRIANJGHITTHENOTETILES.H */
